# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hongker的博客
subtitle: Golang,PHP工程师
description: 做喜欢做的事,不断提高自身的水平。
keywords: "go,php,docker,k8s,微服务,blockchain"
author: hongker
email: xiaok2013@live.com
language:
timezone:


# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://hongker.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
excerpt_link: more
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map: golang

menu:
  主页: /
  Golang: /tags/golang/
  服务化: /tags/micro-service
  kubernetes: /tags/kubernetes
  设计模式: /tags/设计模式
  数据结构与算法: /tags/algorithm
avatar:  static/avatar.jpeg
# SubNav
subnav:
  github: "github.com/hongker"
  # weibo: "#"
  # rss: "#"
  # zhihu: "#"
  qq: "774601526"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:xiaok2013@live.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: yilia

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/hongker/hongker.github.io.git  #这里的网址填你自己的
  branch: master   
  local-dir: public

jsonContnt:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: true
    raw: false
    content: false
    slug: false
    updated: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true


toc:
  maxdepth: 3
  class: toc
  slugify: transliteration
  decodeEntities: false
  anchor: false